### ISSUE TITLE
Log Exceptions sometimes fails with `503` error when uploading xlsx file

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/akf#23]
## Describe the bug and expected behavior 
For both bigger (`09_18`) and smaller (`09_12`) files - we're sometimes seeing this `503` error when running the workflow to generate the exception report xlsx. See issue #15 for background. 
`Error: Message: Service Unavailable`
`Status: 503`
![image](https://github.com/OpenFn/akf/assets/16758106/f136a3b7-c30d-4316-aff5-62f3a599a09f)

## To Reproduce
1. Re-run the workflow for file `09_12` (maybe try running it a couple of times if you don't see the error the first time) starting with job 1 https://openfn.org/projects/akf-bc-aims-testing/jobs/4VQV8Z
2. See failure in step 4a: https://openfn.org/projects/akf-bc-aims-staging/runs/06515c6a-01e4-77b0-b838-97961fcceb11

### expression.js
Work on `testing` branch: 
https://github.com/OpenFn/akf/blob/testing/jobs/logExceptions.js

Adaptor: `msgraph`

### state.json
Job 1: Get Actuals from Sharepoint
```
{
  "configuration": { "See LP: AKF Sharepoint Site" },
  "data": { "NA"},
}```

Job 2: Check If Codes Exist
```
{
  "configuration": { "See LP: AKF Salesforce Sandbox - Partial 2023" },
  "data": { "generated by job 1"},
}```

Job 3: Map & Clean Data
```
{
  "configuration": { NA },
  "data": { "generated by job 2"},
}```

Job 3b: Prepare exceptions report
```
{
  "configuration": { "NA" },
  "data": { "generated by job 2"},
}```

Job 4b: Log exceptions
```
{
  "configuration": { "See LP: AKF Sharepoint Site"  },
  "data": { "generated by job 3b"},
}```

## To test/resolve
Try running the workflow a couple of times in a row to see if you can reproduce... the workflow usually succeeds once we retry it 1-2 times, so maybe it's not worth looking into if we can't pinpoint the problem. 

## Toggl 
Background, context, and business value
The AKF team would like a XLS file to be generated by OpenFn which outputs any errors that were found with their original export. This file will be posted to their Sharepoint site.

The specific request, in as few words as possible
Following the logic of classifying and cleaning rows with different error types in issue https://github.com/OpenFn/akf/issues/13, write these problem rows to a new XLS file which will be posted to the AKF Sharepoint site. See this [example exception report](https://docs.google.com/spreadsheets/d/1pyQc0z446KbODWwr3R7OfLdnFxoVyqaLBQRYGJLlWXo/edit#gid=0.) for the format this file should take and to follow along with the requirements below.

File Name: follow the naming convention openfn_exception_report_YYYY_MM_DD.xls
File Location: posted the file to the "[BC Exception Reports](https://akdngva.sharepoint.com/sites/AKFDataIntegrations/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FAKFDataIntegrations%2FShared%20Documents%2FBC%20Exception%20Reports&viewid=5c371667%2D066c%2D4ad8%2D8e1a%2Da05448979955)" folder on the AKF Sharepoint site.

File contents
The file will contain 10 columns:

Unit
Grant Code
Posting Month
Posting Year
Project Code
Currency
Sum of Actual
Cost Center
Exception Type
Sync Result
What to write to each column for a given row:

The first 8 columns should contain exactly what we received from the BC export.
Then we should add 2 new columns to the report: Exception Type and Sync Result:
(1) Exception Type: Record which exception type was detected for the row using the logic from issue https://github.com/OpenFn/akf/issues/13. The 5 options for this column are Blank Grant Code, Blank Project Code, Blank Cost Center, No Matching Grant Code, and No Matching Project Code. [See this sheet](https://docs.google.com/spreadsheets/d/1pyQc0z446KbODWwr3R7OfLdnFxoVyqaLBQRYGJLlWXo/edit#gid=0) for an example report.

(2) Sync Result: Record the result of the sync depending on the exception type. See below for how the exception type options map to the sync result options. If more than one sync result is detected for a row, the corresponding sync results should be separated by a semi-colon. See [rows 13 and 14](https://docs.google.com/spreadsheets/d/1pyQc0z446KbODWwr3R7OfLdnFxoVyqaLBQRYGJLlWXo/edit#gid=0) for example.
Blank Grant Code - Not imported
Blank Project Code - Imported with default project code
Blank Cost Center - Imported with default cost center
No Matching Grant Code - Not imported
No Matching Project Code - Imported with default project code
Expected data volumes
Max file size = 14.4MB

state.json
Job 1: Get Actuals from Sharepoint

{
  "configuration": { "See LP: AKF Sharepoint Site" },
  "data": { "NA"},
}
Job 2: Check If Codes Exist

{
  "configuration": { NA },
  "data": { "generated by job 1"},
}
Job 3: Map & Clean Data

{
  "configuration": { NA },
  "data": { "generated by job 2"},
}
Job 4: Load Financials to AIMS

{
  "configuration": { "See LP: AKF Salesforce Sandbox - Partial 2023" },
  "data": { "generated by job 3"},
}
Job 5: Log exceptions

{
  "configuration": { "NA" },
  "data": { "generated by job 2"},
}
expression.js
https://github.com/OpenFn/akf/blob/staging/jobs/logExceptions.js

Toggl
AKF BC M8

**Comment by aleksa-krolls** [comment]
@mtuchi @daissatou2 was running into this issue while testing. Not urgent, but when you get to this in the backlog - can you pls check out this msgraph documentation to see if we can do anything in our implementation to avoid this error and potential "throttling"? 
https://learn.microsoft.com/en-us/answers/questions/1090074/getting-error-503-servicenotavailable-in-graph-api

**Comment by mtuchi** [comment]
@aleksa-krolls the `503` means the service is temporarily unavailable for maintenance or is overloaded. 
The proposed solution from Microsoft documentation says
`You may repeat the request after a delay, the length of which may be specified in a Retry-After header`.

**Comment by aleksa-krolls** [comment]
@mtuchi I just want to confirm that you read this article, and don't think there's any strategy in here we can use to improve our implementation? https://learn.microsoft.com/en-us/graph/throttling#best-practices-to-avoid-throttling

If not - then @daissatou2 it might have been the case that AKF Sharepoint instance had a lot of other traffic when you were testing yesterday. So we should expect this error to come up time-to-time, and therefore (1) document the error, (2) include in training, and (3) provide clear guidance on how to re-try the workflow.

**Comment by mtuchi** [comment]
@aleksa-krolls from reading the best practices this is what i got 

HTTP 503 indicates the service isn't ready to handle the request. The common cause is that the service is experiencing more temporary load spikes than expected.

In both cases, a Retry-After header is included in the response indicating how long the calling application should wait before retrying or making a new request. [Learn more from this doc](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)

I need to show @josephjclark this error, he will be able to give me a clear pattern we need to use for such case. But my advice for avoiding this performance error is to use `.csv` file instead of `.xlsx`. Because even if we solve this error with the `re-try` approach we have to enable long running job for `logException` job, because we don't know if the re-try delay will be within the `100sec` limit

**Comment by josephjclark** [comment]
For the record I don't think this is the result of throttling - which is when msgraph will actively reject requests from clients who are making too many calls. If we're being throttled, we should get a `429` error code back, not a `503`. They also say that throttling is rare. So I don't think any of the throttling best practice applies here.

503 means some issue on the msgraph backend - it's busy, for some reason.

It might be reasonable for the job to fail and be manually retried in this case. I mean, if msgraph is experiencing an outage, there's probably not a lot we can do!

However, it would also be reasonable for the adaptor to automatically re-try perhaps 3 times if it gets a 503 error back from the request (this should be handled by `Utils/request`). If we get a retry header we can use that delay, otherwise we can wait maybe 10 seconds. We should console.log each time we retry to give feedback.

I am not really up to speed with where this workflow is right now - but if this happens a lot, and the workflow is making a lot of requests, it may be a good idea to "sleep" between jobs or something to reduce the server load.

**Comment by mtuchi** [comment]
We have decided to take no action for now until face the same problem couple of times 
If this error happens again the following consideration should be discussed 
1. Change the file type from `xlsx` to `csv`.  (`bookType: csv`). This will reduce the file size significantly
2. Update the msgraph adaptor to automatically re-try perhaps 3 times if it gets 503 error back. This option is based [Joe's feedback ☝🏽 ](https://github.com/OpenFn/akf/issues/23#issuecomment-1740639863)

For the time being here is the clear guidance on how to re-try the workflow in case of `503` Error
- Clear state on `getActuals`
- Set the manual cursor date to the file date that your trying to generate exception reports. For example if the file is `bc_actuals_2023_09_12.csv` then update manual cursor in `getActuals` file to `const manualCursor = "2023-09-12"`
- Run the `getActuals`
cc @daissatou2 @aleksa-krolls
